DROP SCHEMA IF EXISTS jc;

CREATE SCHEMA jc;
USE jc;

/* Table: user (Application Users) */
CREATE TABLE user (
    user_id     NVARCHAR(20) NOT NULL,
    password    VARCHAR (60) NOT NULL,
    first_name  NVARCHAR(50) ,
    last_name   NVARCHAR(50) ,
    email       NVARCHAR(70) ,
    security_provider_id INT ,
    default_customer_id  INT ,
    company     NVARCHAR(50) ,
    phone       NVARCHAR(20) ,
    address1    NVARCHAR(100),
    address2    NVARCHAR(100),
    country     NVARCHAR(20) ,
    postal      NVARCHAR(20) ,
    role        NVARCHAR(20) ,
    other_roles NVARCHAR(80) ,
    is_active   SMALLINT  ,
    is_blocked  SMALLINT  ,
    secret_question     NVARCHAR(100),
    secret_answer       NVARCHAR(100),
    enable_beta_testing SMALLINT ,
    enable_renewal      SMALLINT ,
    CONSTRAINT user_id PRIMARY KEY(user_id)
);

CREATE TABLE clients (
    id                            LONG  NOT NULL AUTO_INCREMENT,
    is_corporate                  SMALLINT NOT NULL,
    name                          VARCHAR(100) NOT NULL,
    created_at                    TIMESTAMP NOT NULL,
    updated_at                    TIMESTAMP NOT NULL,
    client_price_group            VARCHAR(20) NOT NULL,
    sales_agent_id                LONG NOT NULL,
    fidelity_card_id              LONG,
    fidelity_group                NVARCHAR(20),
    last_billing_date             DATE NOT NULL,
    billing_rate_index            FLOAT NOT NULL,
    email_confirmation            SMALLINT NOT NULL,
    days_from_last_bill           INTEGER NOT NULL,
    email                         VARCHAR(70) NOT NULL,
    assigned_center               NVARCHAR(50) NOT NULL,
    country                       NVARCHAR(20) NOT NULL,
    country_code                  NVARCHAR(20) NOT NULL,
    address                       NVARCHAR(200) NOT NULL,
    contact_phone                 NVARCHAR(20) NOT NULL,
    contact                       NVARCHAR(50) NOT NULL,
    payment_method                VARCHAR(20) NOT NULL,
    payment_due_in                INTEGER NOT NULL,
    payment_notification          INTEGER NOT NULL,
    contract_nr                   LONG NOT NULL,
    contract_expiration_date      DATE NOT NULL,
    reg_code                      VARCHAR(20) NOT NULL,
    is_vat_applicable             SMALLINT NOT NULL,
    balance                       FLOAT NOT NULL,
    debit                         FLOAT NOT NULL,
    credit                        FLOAT NOT NULL,
    credit_approved_limit         FLOAT NOT NULL,
    credit_limit                  FLOAT NOT NULL,
    legal_notice_received_on      TIMESTAMP,
    legal_notice_sent_on          TIMESTAMP,
    legal_notice_outcome          VARCHAR(15),
    cip_received_on               TIMESTAMP,
    cip_sent_on                   TIMESTAMP,
    cip_outcome                   VARCHAR(15),
    fin_notice_received_on        TIMESTAMP,
    fin_notice_sent_on            TIMESTAMP,
    fin_outcome                   VARCHAR(15),
    org_type                      VARCHAR(100) NOT NULL,
    sales_amount                  FLOAT,
    comment                       NVARCHAR(200),
    CONSTRAINT id PRIMARY KEY(id)
);