runtime: java
env: flex
runtime_config:
  jdk: openjdk8
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgres"
handlers:
  - url: /.*
    script: this field is required, but ignored
resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
manual_scaling:
  instances: 1
network:
  forwarded_ports:
    - 9119
